from typing import List,Optional
from pydantic import BaseModel,Field

class InvoiceLine(BaseModel):
    line_number: Optional[int] = Field(default=None,description="Line number on the invoice")
    description: Optional[str] = Field(default=None,description="Description of the goods or services")
    sku: Optional[str] = Field(default=None,description="Item SKU or part number")
    quantity: Optional[float] = Field(default=None,description="Quantity invoiced")
    unit_of_measure: Optional[str] = Field(default=None,description="Unit of measure for the quantity")
    unit_price: Optional[float] = Field(default=None,description="Unit price for this line")
    line_total: Optional[float] = Field(default=None,description="Total amount for this line")
    tax_rate: Optional[float] = Field(default=None,description="Tax rate for this line as a percentage")
    tax_code: Optional[str] = Field(default=None,description="Tax code for this line")
    po_number: Optional[str] = Field(default=None,description="Purchase order number for this line")
    po_line_number: Optional[str] = Field(default=None,description="Purchase order line identifier")

class InvoiceExtract(BaseModel):
    supplier_name: Optional[str] = Field(default=None,description="Name of the supplier or vendor")
    supplier_tax_id: Optional[str] = Field(default=None,description="Tax identification number of the supplier")
    supplier_address: Optional[str] = Field(default=None,description="Address of the supplier")
    buyer_name: Optional[str] = Field(default=None,description="Name of the buyer or company receiving the invoice")
    company_code: Optional[str] = Field(default=None,description="Internal company or entity code")
    cost_center: Optional[str] = Field(default=None,description="Cost center or department charged for this invoice")
    invoice_number: Optional[str] = Field(default=None,description="Invoice number assigned by the supplier")
    invoice_date: Optional[str] = Field(default=None,description="Invoice date in ISO format if possible")
    due_date: Optional[str] = Field(default=None,description="Payment due date")
    currency: Optional[str] = Field(default=None,description="Currency code for this invoice, for example USD or EUR")
    payment_terms: Optional[str] = Field(default=None,description="Payment terms such as Net 30")
    subtotal_amount: Optional[float] = Field(default=None,description="Subtotal before tax and charges")
    tax_amount: Optional[float] = Field(default=None,description="Total tax amount")
    shipping_amount: Optional[float] = Field(default=None,description="Shipping or freight charges")
    discount_amount: Optional[float] = Field(default=None,description="Total discount amount")
    total_amount: Optional[float] = Field(default=None,description="Total invoice amount due")
    po_number: Optional[str] = Field(default=None,description="Main purchase order number referenced on the invoice")
    bank_account: Optional[str] = Field(default=None,description="Bank account or IBAN for payment")
    swift_bic: Optional[str] = Field(default=None,description="Bank SWIFT or BIC code")
    remittance_reference: Optional[str] = Field(default=None,description="Reference to include with the payment")
    invoice_type: Optional[str] = Field(default=None,description="Type of invoice such as invoice or credit note")
    lines: List[InvoiceLine] = Field(default_factory=list,description="Line items on the invoice")
